---
- name: Copy docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/tmp/docker-compose.yml"

- name: Docker compose up
  shell: "docker compose -f /tmp/docker-compose.yml up -d"

- name: change ownership of a directory
  file:
    path: "{{ data_dir }}"
    owner: "1000"
    group: "1000"
    state: directory
    recurse: yes
    mode: "0755"
