---
#- hosts: registry
#  roles:
#     - role: install-docker
#     - role: docker-registry
#    
#- hosts: nexus
#  roles:
#    - role: install-docker
#    - role: nexus
#
- hosts: gitlab
  roles:
    # - role: install-docker
    - role: gitlab 
