---
##-------Uncomment if needs to set dns
#- name: Remove symlink resolv.conf
#  file:
#    path: /etc/resolv.conf
#    state: absent
#  ignore_errors: yes
#
#- name: Copy resolv.conf
#  template:
#    src: resolv.conf.j2
#    dest: /etc/resolv.conf
#    mode: "0644"
#
- name: Apt update
  apt:
    update_cache: yes

- name: Added ca and curl
  apt:
    name:
      - ca-certificates
      - curl

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    mode: '0755'

- name: Download Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

- name: Set read permissions for all users on docker.asc
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
    state: file

- name: Add Docker repository to sources list
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | tee /etc/apt/sources.list.d/docker.list

- name: Apt update
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify:
    - start-docker
    - enable-docker

